name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tectonic
        run: make

      # - name: Upload pdf
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: book
      #     path: book.pdf

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@4.1.7
      #   with:
      #     branch: gh-pages
      #     folder: build
