name: CI

on: push

jobs:
  build:
    runs-on: dxjoke/tectonic-docker@sha256:8397f92406320bfff8da95cbec41a683a956c6dbbe870268c79a887080dcbc4f

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"
