name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up git repository
        uses: actions/checkout@v2

      - name: add tectonic support
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate book pdf and html page
        run: make

      - name: generate epub
        uses: docker://pandoc/core:2.9
          with:
            args: "--help" # gets appended to pandoc command
        run: make epub

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
